### PR TITLE
fix: clean up compiler warnings

### PR DESCRIPTION
**Pull request by mehtaculous**
Majority of these compiler warnings are for unused function parameters and local variables

Simple solution was to just comment them out for now

Also updated `foundry.toml` to ignore warnings from `node_moules` and `integrations` directories

### CODE REVIEW

**Comment by kopy-kat** [comment]
looks good, thanks! could you please run `pnpm lint:sol` to make sure the ci passes

**Comment by mehtaculous** [comment]
some additional fixes after running the linter:
- `solhint` requests that commas come before the actual parameter name when it is commented out (I personally find this to be a bit weird but can leave it as is or simply just remove the commented out name to avoid any possible confusion)
- updated 2 requires to custom reverts => this also should save some gas
- removed a few unused imports from integration contracts
- updated `solhint.json` by setting `no-global-import` to off

**Comment by mehtaculous** [comment]
also updated the `README` to include the lint command

**Comment by kopy-kat** [comment]
great thank you, could you also just fix the conflicts (the `ExtensibleFallbackHandler.sol`) was actually just removed since it is an outdated component

**Comment by kopy-kat** [comment]
lgtm and thanks again

**Pull request merged**
